config/routes.rb
Bookoid::Application.routes.draw do
  devise_for :users
  resources :genres

  resources :books do
    get :autocomplete_book_title, :on => :collection
  end
  controller :books do
    get "user_books" => :user_books, :as => "user_books"
    get "add_book/:id" => :add_book, :as => "add_book"
    get "drop_book/:id" => :drop_book, :as => "drop_book"
  end

  controller :staff do
    get "staff" => :index, :as => "staff"
  end

  root :to => 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base

  belongs_to :genre
  has_many :readers
  has_many :users, :through => :readers

  validates_uniqueness_of :title
  validates :title, :description, :genre, :presence => true

  has_attached_file :cover, :styles => { :medium => "300x400", :thumb => "100x200" }

  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

end

app/models/genre.rb
class Genre < ActiveRecord::Base

  has_many :books

  def self.dropdown
    @all_genres = Genre.all
    @genres = []
    @all_genres.each do |gen|
      @genres << [gen.title, gen.id]
    end
    return @genres
  end

end

app/models/reader.rb
class Reader < ActiveRecord::Base
  
  belongs_to :user  # foreign key - user_id
  belongs_to :book  # foreign key - book_id

  scope :find_by_user_and_book, lambda { |book_id, user_id| where(:book_id => book_id, :user_id => user_id) }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :is_admin

  has_many :readers
  has_many :books, :through => :readers

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate_admin
    unless current_user.is_admin?
      flash[:error] = "Administrator rights needed"
      redirect_to root_path
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:index]
  before_filter :prepare

  autocomplete :book, :title, :full => true

  def index
    @books = Book.search(params[:search]).paginate(:per_page => 10, :page => params[:page])
    @book = Book.new
  end

  def user_books
    @books = current_user.books.paginate(:per_page => 3, :page => params[:page])
  end

  def add_book
    Reader.create(:book_id => params[:id], :user_id => current_user.id)
    respond_to do |format|
      format.html {redirect_to :back}
      #format.js {}
    end
  end

  def drop_book
    @drop_book = Reader.find_by_user_and_book(params[:id], current_user.id).last
    respond_to do |format|
      if @drop_book.destroy
        format.html {redirect_to :back}
        #format.js {}
      end
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(params[:book])
    @book.users << current_user

    respond_to do |format|
      if @book.save
        Reader.create(:book_id => @book.id, :user_id => current_user.id)
        format.html { redirect_to(books_path, :notice => '') }
        format.xml  { render :xml => @book, :status => :created, :location => @book }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to(books_path, :notice => "") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to(books_url, :notice => "") }
      format.xml  { head :ok }
      format.js   {          }
    end
  end

  private # -------------------------------------------------------------------------

  def prepare
    @genres = Genre.dropdown
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :authenticate_admin

  layout "staff"

  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(params[:genre])

    respond_to do |format|
      if @genre.save
        format.html { redirect_to(genres_path, :notice => '') }
        format.xml  { render :xml => @genre, :status => :created, :location => @genre }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @genre.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    respond_to do |format|
      if @genre.update_attributes(params[:genre])
        format.html { redirect_to(genres_path, :notice => "") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @genre.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to(genres_url, :notice => "") }
      format.xml  { head :ok }
    end
  end

end

app/controllers/staff_controller.rb
class StaffController < ApplicationController
  
  layout 'staff'

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate_user!

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.haml
%br

  = f.label :book_title
  = f.text_field :title,:size => 70

  %br
  %br
  = f.label :author
  = f.text_field :author

  = f.label :year
  = f.date_select :year, :order => [:year], :start_year => 1, :prompt => { :year => '' }

  = f.label :genre
  = f.select :genre_id, @genres


  %br
  %br
  = f.label :description
  %p= f.text_area :description

  = f.label :cover
  = f.file_field :cover

  %br
  %br
  = f.submit "OK"
  |
  = link_to "Back", books_path

app/views/books/add_book.js.erb
$("#book_<%= @book.id %>").fadeOut();
$("#book_<%= @book.id %>").remove();

app/views/books/destroy.js.erb
$("#book_<%= @book.id %>").fadeOut();
$("#book_<%= @book.id %>").remove();

app/views/books/drop_book.js.erb
$("#book_<%= @book.id %>").fadeOut();
$("#book_<%= @book.id %>").remove();

app/views/books/edit.haml
= form_for @book, :url => book_path(@book), :html => { :method => :put }  do |f|
  = render :partial => "form", :locals => {:f => f, :action => "edit"}

app/views/books/index.haml
%br/

%div#book_list
  = form_tag books_path, :autocomplete => 'off', :method => 'get' do  #autocomplete 'off' is just for browser autocomplete
    = label_tag :find_book_by_title
    =# text_field_tag :search, params[:search]
    = autocomplete_field_tag 'search', '', autocomplete_book_title_books_path, :size => 35#, :"data-delimiter" => ',' # 'search'  is using like params[:search]
    = submit_tag "Search", :name => nil
    =# text_field_tag 'title', '', :autocomplete => books_autocomplete_book_title_path

  %br
  or

  %h3= link_to 'Add book', new_book_path

  %br/
  =will_paginate @books

  %table.round{:cellpadding=>5,:cellspacing=>5}
    %tr
      %th

      - @books.each do |book|
        %tr{:class => cycle('list_line_odd', 'list_line_even')}
          %td= link_to image_tag(book.cover(:thumb), :border => "1"), book_path(book)
          %td= book.title
          -if user_signed_in?
            %td.list_actions
              = current_user.books.include?(book) ? link_to("Delete from my list", drop_book_path(book)) : link_to("Add to my list", add_book_path(book))
              %br/
              -if current_user.is_admin?
                = link_to "Edit", edit_book_path(book)
                %br/
                = link_to 'Delete', book_path(book), :confirm => 'Delete book?', :method => :delete

=will_paginate @books

app/views/books/new.haml
%h2 Add book

= render :partial => "shared/errors", :locals => {:obj => @book}

= form_for @book do |f|
  = render :partial => "form", :locals => {:f => f, :action => "new"}

app/views/books/show.haml
=image_tag(@book.cover, :align => 'left', :border => "2")

%div.bookshow
  Title:
  =@book.title

  %br/
  Author:
  = @book.author

  %br/
  Year:
  = @book.year == nil ? 'unknown' : @book.year

  %br/
  Genre:
  = @book.genre.title

  %br/
  Description:
  = @book.description

app/views/books/user_books.haml
%h3= link_to 'Add book', new_book_path

%br/
=will_paginate @books

%br/
%table.round{:cellpadding=>5,:cellspacing=>5}
  %tr
    %th

    - @books.each do |book|
      %tr#book
      %td= link_to image_tag(book.cover(:thumb), :border => "1"), book_path(book)
      %td= book.title
      %td= link_to("Delete from my list", drop_book_path(book))

%br/
=will_paginate @books

app/views/genres/_form.haml
%h2 New genre
%br

  = f.label :genre_title
  = f.text_field :title

  %br
  %br

  = f.submit "OK"
  |
  = link_to "Back", genres_path

app/views/genres/index.haml
%h3= link_to 'Add genre', new_genre_path

%table{:cellpadding=>5,:cellspacing=>5}
  %tr
    %th Title

    - @genres.each do |genre|
      = form_for genre do |f|
        %tr
        %td= f.text_field :title, :value => genre.title
        %td= link_to "Edit", edit_genre_path(genre)
        %td= link_to 'Delete', genre_path(genre), :confirm => 'Delete genre?', :method => :delete

app/views/genres/new.haml
= form_for @genre do |f|
  = render :partial => "form", :locals => {:f => f, :action => "new"}

app/views/layouts/application.haml
!!!
%html
  %head
    %title Bookoid
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    %link{:href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/themes/ui-lightness/jquery-ui.css", :rel => "stylesheet", :type => "text/css"}
    = csrf_meta_tags
  %body
    = render :partial => "shared/login_tab"
    = render :partial => "shared/to_admin" if user_signed_in? && current_user.is_admin
    %br/
    = render :partial => "shared/tab"
    = render :partial => "shared/alerts_notices"
    = yield

app/views/layouts/staff.haml
%html{"xmlns"=>"http://www.w3.org/1999/xhtml", "xml:lang"=>"en"}
%head
  %titleBookoid
  = stylesheet_link_tag    "application"
  = javascript_include_tag "application"
  = csrf_meta_tags

  %body

  = render :partial => "shared/login_tab"
  = render :partial => "shared/to_site" if user_signed_in? && current_user.is_admin

%br

  = render :partial => "shared/staff_tab"

= yield

app/views/shared/_alerts_notices.html.haml
%p.notice= notice
%p.notice= flash[:error]

app/views/shared/_errors.haml
- if obj.errors.any?
  #error_explanation
    %h2
      = pluralize(obj.errors.count, "error")
      prohibited category from being saved:
    %ul
      - obj.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_login_tab.html.erb
  <div align="center">
     <% if user_signed_in? %>
		   You entered as <b><%= current_user.email %></b>. <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
	    <% else %>
		   <%= link_to "Log in", new_user_session_path %> | <%= link_to "Registration", new_user_registration_path %>
	   <% end %>
  </div>

app/views/shared/_staff_tab.haml
= link_to "Genres", genres_path
%hr

app/views/shared/_tab.haml
%hr
= link_to "All books", books_path
- if user_signed_in?
    |
    = link_to "My books", user_books_path
%hr

app/views/shared/_to_admin.haml
.staff_link{:style => "text-align:right"}= link_to "Enter to the staff part", staff_path

app/views/shared/_to_site.haml
.staff_link{:style => "text-align:right"}= link_to "Enter to the site", root_path